### ISSUE TITLE
Add some documentation

### ISSUE THREAD

**Issue by tomekowal** [smeevil/flycheck-elixir-testresult#1]
Hi!

I checked your project and it looks very promising. I wanted to build elixir with `mix compile` and have its errors pop out in flycheck, but since `mix test` also compiles stuff I could use your project instead of writing something myself.

I installed the package for emacs and put helper script in my path, but I am not sure where do I put formatter and how can I configure it. Without the formatter file paths are relative so it doesn't work.

Thanks for your time!

**Comment by smeevil** [comment]
Hi Tomekowal,

I was just experimenting with this, but eventually stopped using spacemacs. I hope this was a good starting point for you to work on :) 

I'm removing the repo since it will not be maintained.

Gerard
